[feat-9] Ajout des points Velov sur la carte de lyon
Zenika/ez-velov pull request #25
Opened 2022-05-12 08:44 UTC by RemyDavid0

2022-05-12 16:03 UTC, Oonag commented on back/src/main/java/com/zenika/lyon/ezvelov/domain/station/Position.java
> +    public double longitude;
What mais d'où il est public lui ? Dans quel cadre tout pourrait le faire et pk tu ne dois pas le faire ici ?

2022-05-12 16:11 UTC, Oonag commented on back/src/main/java/com/zenika/lyon/ezvelov/infrastructure/repository/station/StationEntityMapper.java
> +        return new Station(0, positionEntityMapper.positionEntitytoPosition(stationEntity.getPosition()));
Pk 0 et pas 1 ?

2022-05-12 16:13 UTC, Oonag commented on back/src/test/java/com/zenika/lyon/ezvelov/infrastructure/provider/station/StationProviderMock.java
> +                0, new com.zenika.lyon.ezvelov.domain.station.Position(4.815747, 45.743317)));
42

2022-05-12 16:15 UTC, Oonag commented on back/src/test/java/com/zenika/lyon/ezvelov/infrastructure/provider/station/StationProviderTest.java
> +class Station {
Lol tu test des tests ? Tes tests disent "en admettons que j'ai raison, alors j'ai raison" C'est beau

2022-05-12 16:16 UTC, Oonag commented on front/src/app/map/map.component.ts
> +        stations.forEach((station) => {
Ca aurait été sympa de l'extraire dans une méthode pour que la lecure soit plus simple :)

2022-05-13 07:46 UTC, RemyDavid0 commented on back/src/main/java/com/zenika/lyon/ezvelov/application/controller/station/PositionDto.java
> +public class PositionDto {
je changerai

2022-05-13 07:46 UTC, RemyDavid0 commented on back/src/main/java/com/zenika/lyon/ezvelov/application/controller/station/StationController.java
> +        return listStationDto;
ok

2022-05-13 07:47 UTC, RemyDavid0 commented on back/src/main/java/com/zenika/lyon/ezvelov/application/controller/station/StationDtoMapper.java
> +        return new Station(0, positionDtoMapper.positionDtotoPosition(stationDto.positionDto()));
j'ai pansé que ça serait un numéro par défaut

2022-05-13 07:50 UTC, RemyDavid0 commented on back/src/main/java/com/zenika/lyon/ezvelov/domain/station/Station.java
> +public class Station {
je vais corriger tout ça

2022-05-13 07:50 UTC, RemyDavid0 commented on back/src/main/java/com/zenika/lyon/ezvelov/infrastructure/provider/station/StationProvider.java
> +        String strResponse = restTemplate.getForObject(
ok je vais modifier

2022-05-13 07:51 UTC, RemyDavid0 commented on back/src/main/java/com/zenika/lyon/ezvelov/infrastructure/provider/station/StationProvider.java
> +        Gson gson = new Gson();
ok je vais changer

2022-05-13 07:52 UTC, RemyDavid0 commented on back/src/test/java/com/zenika/lyon/ezvelov/infrastructure/provider/station/StationProviderTest.java
> +        List<Station> station = gson.fromJson(givenJsonStation, stationListType);
yes

2022-05-13 08:59 UTC, RemyDavid0 commented on back/src/main/java/com/zenika/lyon/ezvelov/application/controller/station/StationController.java
> +    private StationDtoMapper stationDtoMapper;
ok

2022-05-13 09:43 UTC, RemyDavid0 commented on back/src/main/java/com/zenika/lyon/ezvelov/domain/station/Position.java
> +    public double longitude;
c'était clairement une faute d'inattention de le mettre public
Et on ne doit pas y mettre en public car on ne veux pas que la variable soit accessible de partout

2022-05-13 09:56 UTC, RemyDavid0 commented on back/src/test/java/com/zenika/lyon/ezvelov/infrastructure/provider/station/StationProviderMock.java
> +    public List<com.zenika.lyon.ezvelov.domain.station.Station> getAllStations() {
ok

2022-05-13 12:30 UTC, RemyDavid0 commented on back/src/main/java/com/zenika/lyon/ezvelov/application/controller/station/StationDtoMapper.java
> +package com.zenika.lyon.ezvelov.application.controller.station;
okay, j'ai fait un package pour la position

2022-05-13 12:52 UTC, RemyDavid0 commented on back/src/main/java/com/zenika/lyon/ezvelov/infrastructure/repository/station/PositionEntity.java
> +public class PositionEntity {
je change ça en record

2022-05-13 12:55 UTC, RemyDavid0 commented on back/src/test/java/com/zenika/lyon/ezvelov/infrastructure/provider/station/StationProviderTest.java
> +class Station {
?

2022-05-13 13:37 UTC, RemyDavid0 commented on back/src/main/java/com/zenika/lyon/ezvelov/infrastructure/repository/station/StationEntityMapper.java
> +        return new Station(0, positionEntityMapper.positionEntitytoPosition(stationEntity.getPosition()));
ici on peut garder le numéro de station intacte, je change ça

2022-05-23 08:15 UTC, Oonag requested changes

2022-05-23 08:15 UTC, Oonag commented on back/src/main/java/com/zenika/lyon/ezvelov/application/controller/station/StationController.java
> +    public List<StationDto> getAllStations(){
Va falloir que tu fasse gaffe à l'indentation, c'est trop chiant et t'as des raccourcis pour ça

2022-05-23 08:15 UTC, Oonag commented on back/src/main/java/com/zenika/lyon/ezvelov/application/controller/station/StationController.java
> +        List<Station> listStation;
T'es sérieux ? T'as besoin de 3 lignes pour faire ça ?

2022-05-23 08:15 UTC, Oonag commented on back/src/main/java/com/zenika/lyon/ezvelov/application/controller/station/StationDtoMapper.java
> +    StationDto stationToStationDto(Station station){
toujours indentation

2022-05-23 08:15 UTC, Oonag commented on back/src/main/java/com/zenika/lyon/ezvelov/application/controller/station/StationDtoMapper.java
> +    StationDto stationToStationDto(Station station){
Pk package private ? pk pas mais je ne suis pas certain que tu comprenne pk

2022-05-23 08:15 UTC, Oonag commented on back/src/main/java/com/zenika/lyon/ezvelov/domain/station/Station.java
> +public record Station(Integer number, Position position){
Au final je vais être chiant mais ici je voudrais un id plutôt qu'un nombre.
Pk ? parce que "number" ça veut rien dire et parce qu'on ne devrait pas laisser ce nom sous prétexte qu'une api externe fait de la merde.
Du coup coté application ça sera également un id et tes front devs te seront reconnaissants ;)

2022-05-23 08:59 UTC, RemyDavid0 commented on back/src/main/java/com/zenika/lyon/ezvelov/application/controller/station/StationController.java
> +        List<Station> listStation;
effectivement, ça se fait en 1 seule

2022-05-23 08:59 UTC, RemyDavid0 commented on back/src/main/java/com/zenika/lyon/ezvelov/domain/station/Station.java
> +public record Station(Integer number, Position position){
okay

2022-05-30 10:59 UTC, Oonag approved these changes

2022-05-30 12:21 UTC, merged