[feat-58] mise a jour du front, ajout logo, background
Zenika/ez-velov pull request #26
Opened 2022-05-19 13:16 UTC by RemyDavid0

2022-05-23 08:31 UTC, Oonag requested changes

2022-05-23 08:31 UTC, Oonag commented on front/src/app/app.component.html
> +    <li> <img src="../assets/Horizontal_Black_Logo-Zenika.png"></li>
Nan mais sérieux tu peux pas me renommer les images our que ça soit clair ? ^^

2022-05-23 08:31 UTC, Oonag commented on front/src/index.html
> +    <img class="background" src="./assets/pexels-daria-shevtsova.jpg">
Ste plé un autre nom.... ON COMPREND RIEN

2022-05-23 08:31 UTC, Oonag commented on front/src/app/map/map.component.scss
> +  height: 95vh;
vh ? c'est quoi ce truc ? Généralement on utilise px ou em mais pas des trucs de l'espace

2022-05-23 08:31 UTC, Oonag commented on front/src/index.html
> +  <main>
Qqun t'as aidé ou tu l'as fait seul ?
J'aurais pas fait comme ça

2022-05-23 08:31 UTC, Oonag commented on front/src/styles.scss
> +  z-index: 2;
C'est quoi celui-ci ?

2022-05-23 08:31 UTC, Oonag commented on front/src/app/app.component.scss
>  * {
On avait parlé d'un bandeau blanc au niveau du titre non ?
Le welcome Mister Nobody devrait être centré sous le titre.

2022-05-23 08:41 UTC, RemyDavid0 commented on front/src/index.html
> +  <main>
(+bandeau blanc)

2022-05-23 08:44 UTC, RemyDavid0 commented on front/src/styles.scss
> +  z-index: 2;
(rendre l'image avec l'opacité de base)

2022-05-23 08:46 UTC, RemyDavid0 commented on front/src/app/app.component.scss
>  * {
ok je vais le mettre en haut a droite

2022-05-23 08:46 UTC, RemyDavid0 commented on front/src/app/map/map.component.scss
> +  height: 95vh;
j'utiliserai les px/em

2022-05-30 10:56 UTC, Oonag approved these changes

2022-05-30 12:13 UTC, merged