Feat 4/details point velov
Zenika/ez-velov pull request #27
Opened 2022-05-25 12:29 UTC by RemyDavid0

2022-05-30 12:23 UTC, RemyDavid0 commented on front/src/app/map/map.component.ts
> +              .setHTML('capacité :' + capacity.toString()
également mettre la barre de recherche en dehors de la carte

2022-06-01 09:50 UTC, Oonag requested changes

2022-06-01 09:50 UTC, Oonag commented on front/src/app/map/map.component.ts
> +              .setHTML('capacité :' + capacity.toString() + '<br>'
toString sur des number BA VOYONS

2022-06-01 09:50 UTC, Oonag commented on front/src/app/map/map.component.ts
> +              .setHTML('capacité :' + capacity.toString() + '<br>'
J'aimerais bien que le texte soit exporté dans une méthode pour que ça soit plus lisible.

2022-06-08 09:01 UTC, Oonag approved these changes

2022-06-08 09:45 UTC, merged