[feat-2] affichage geolocalisation utilisateur
Zenika/ez-velov pull request #29
Opened 2022-05-31 13:27 UTC by RemyDavid0

La localisation est parfois imprécise, c'est pourquoi j'ai activé une option qui indique si la position affiché est approximative ou non

2022-06-01 09:57 UTC, Oonag requested changes

2022-06-01 09:57 UTC, Oonag commented on front/src/app/map/map.component.ts
> +  locateTheUserOnMap(map: mapboxgl.Map): void {
Nom de méthode -> geolocateUser
J'aimerais que la map soit centrée sur l'utilisateur dés qu'on entre dans l'application :P

2022-06-01 10:03 UTC, RemyDavid0 commented on front/src/app/map/map.component.ts
> +  locateTheUserOnMap(map: mapboxgl.Map): void {
je vais regarder ça

2022-06-01 12:39 UTC, Oonag requested changes

2022-06-01 12:39 UTC, Oonag commented on front/src/app/map/map.component.ts
> +  geolocateUser(map: mapboxgl.Map): void {
Ok je viens de comprendre.
Tu mélange deux choses :
- ici tu ajoute le bouton de geolocalisation. Ca fait une méthode initGeolocator
- tu trigger le bouton automatiquement au chargement. C'est un autre action qui est séparée de la première.

Moi j'aurais créé un champ privé geolocator que je ferais trigger à la fin du init.
Pas certain que ça marche mais on peut essayer

2022-06-08 09:36 UTC, Oonag approved these changes

2022-06-08 12:07 UTC, merged