Feat 16-17-18/itinéraire pied ou vélo et affichage temps de trajet
Zenika/ez-velov pull request #31
Opened 2022-06-16 09:32 UTC by RemyDavid0

2022-06-16 12:30 UTC, Oonag commented on front/src/app/map/map.component.ts
> +    let buttonStart = document.getElementById('buttonStart');
C'est quoi buttonStart et buttonEnd ? je lis même pas la suite du fichier.

2022-06-16 12:32 UTC, Oonag commented on front/src/styles.scss
> +  background-color: #ffffff;
Pk le background est encore dans les fichiers s'il n'est plus utilisé ?

2022-06-16 12:53 UTC, Oonag requested changes

2022-06-16 12:53 UTC, Oonag commented on front/src/app/map/map.component.html
> +        <input type="radio" id="recherche" name="trajet">
id="recherche" c'est tellement limpiiiiiide !
name="trajet" ici ?

rechercheTrajet vs recherchePosition c'est quand même plus évident non ?
J'arrête de lire,

2022-06-16 13:37 UTC, RemyDavid0 reviewed
On a des type any dans le ts, faute de mieux

2022-06-22 13:00 UTC, Oonag approved these changes

2022-06-22 13:09 UTC, merged